// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[...templates].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_500.tsx";
import * as $3 from "./routes/_app.tsx";
import * as $4 from "./routes/api/[...template].ts";
import * as $5 from "./routes/api/list.ts";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/SearchBar.tsx";

const manifest = {
  routes: {
    "./routes/[...templates].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_500.tsx": $2,
    "./routes/_app.tsx": $3,
    "./routes/api/[...template].ts": $4,
    "./routes/api/list.ts": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/SearchBar.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
