// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_templates_ from "./routes/[...templates].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_template_ from "./routes/api/[...template].ts";
import * as $api_list from "./routes/api/list.ts";
import * as $index from "./routes/index.tsx";
import * as $SearchBar from "./islands/SearchBar.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[...templates].tsx": $_templates_,
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/[...template].ts": $api_template_,
    "./routes/api/list.ts": $api_list,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/SearchBar.tsx": $SearchBar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
